###
GET http://localhost:3000/api HTTP/1.1

###
GET http://localhost:3000/api/5 HTTP/1.1

###
POST http://localhost:3000/api HTTP/1.1
Content-Type: application/json

{
    "nombre": "Leo",
    "apellido": "Messi",
    "cama": 25,
    "fecha_ingreso": "2022-08-02",
    "diagnostico": "Lesión de tobillo"
}

###
DELETE http://localhost:3000/api/6 HTTP/1.1

###
PUT http://localhost:3000/api/5 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Rigoberto",
    "apellido": "Uran",
    "cama": 20,
    "fecha_ingreso": "2022-08-05",
    "diagnostico": "Se rompio el brazo en una caida"
}